build_task:
  container:
    dockerfile: Dockerfile
    cpu: 4
    memory: 6G
  build_script: |
    git clone --depth 1 https://github.com/Spottedleaf/Tuinity.git &&
    cd Tuinity &&
    git config --global user.email "you@example.com" &&
    git config --global user.name "Your Name" &&
    git submodule update --init --recursive &&
    ./tuinity jar
  artifacts:
    path: "Tuinity/tuinity-paperclip.jar"
